from django.urls import path,include
from .views import *

urlpatterns = [
    path('',polynomials_calculator, name='polynomials_calculator'),
    path('remainder-theorem-calculator/',remainder_theorem_calculator, name='remainder_theorem_calculator'),
    path('solve-<str:num1>-by-<str:num2>/',remainder_theorem_detail, name='remainder_theorem_detail'),
    path('adding-polynomials-calculator/',poly_add, name='poly_add'),	
    path('adding-polynomials-<str:num1>/',poly_add_func,name='poly_add_func'),
    path('subtracting-polynomials-calculator/',poly_sub, name='poly_sub'),	
    path('subtracting-polynomials-<str:num1>/',poly_sub_func,name='poly_sub_func'),
    path('multiplying-polynomials-calculator/',poly_mul, name='poly_mul'),	
    path('multiplying-polynomials-<str:num1>/',poly_mul_func,name='poly_mul_func'),
    path('dividing-polynomials-calculator/',poly_div, name='poly_div'),	
    path('dividing-polynomials-<str:num1>/',poly_div_func,name='poly_div_func'),
    path('determining-if-the-expression-is-a-polynomial-calculator/',poly_check, name='poly_check'),	
    path('is-<str:num1>-a-polynomial/',poly_check_func,name='poly_check_func'),
    path('degree-of-a-polynomial-calculator/',poly_degree, name='poly_degree'),	
    path('degree-of-a-polynomial-<str:num1>/',poly_degree_func,name='poly_degree_func'),
    path('polynomial-in-ascending-order-calculator/',poly_ascend,name='poly_ascend'),
    path('polynomial-in-ascending-order-<str:num1>/',poly_ascend_func,name='poly_ascend_func'),
    path('polynomial-in-descending-order-calculator/',poly_descnd,name='poly_descnd'),
    path('polynomial-in-descending-order-<str:num1>/',poly_descnd_func,name='poly_descnd_func'),
    path('leading-term-of-a-polynomial-calculator/',leading_poly, name='leading_poly'),
    path('leading-term-of-a-polynomial-<str:num1>/',leading_poly_func,name='leading_term'),
    path('factoring-multi-variable-polynomials-calculator/',factor_poly, name='factor_poly'),
    path('factoring-multi-variable-polynomials-<str:num1>/',factor_poly_func,name='factor_poly_func'),
    path('gcf-of-polynomials-calculator/',gcf_poly, name='gcf_poly'),
    path('gcf-of-polynomials-<str:num1>/',gcf_poly_func,name='gcf_poly_func'),
    path('factor-out-gcf-from-polynomials-calculator/',gcf_fact, name='gcf_fact'),
    path('factor-out-gcf-from-polynomials-<str:num1>/',gcf_fact_func,name='gcf_fact_func'),
    path('lcm-of-polynomials-using-gcf-calculator/',poly_lcm, name='poly_lcm'),
    path('lcm-of-polynomials-<str:num1>-and-<str:num2>-using-gcf/',poly_lcm_func,name='poly_lcm_func'),
    path('determining-if-polynomial-is-prime-calculator/',poly_prime, name='poly_prime'),
    path('determining-if-<str:num1>-polynomial-is-prime/',poly_prime_func,name='poly_prime_func'),
    path('factoring-binomials-as-sum-or-difference-of-cubes-calculator/',poly_factor_cube, name='poly_factor_cube'),
    path('factoring-binomials-as-sum-or-difference-of-cubes-<str:num1>/',poly_factor_cube_func,name='poly_factor_cube_func'),
    path('factoring-difference-square-polynomial-calculator/',poly_factor_sqr, name='poly_factor_sqr'),
    path('factoring-difference-square-polynomial-<str:num1>/',poly_factor_sqr_func,name='poly_factor_sqr_func'),
    path('binomial-expansion-calculator/',poly_expn, name='poly_expn'),
    path('binomial-expansion-of-<str:num1>/',poly_expn_func,name='poly_expn_func'),
    path('factoring-over-complex-numbers-calculator/',comp_fact, name='comp_fact'),
    path('factoring-<str:num1>-over-complex-numbers/',comp_fact_func,name='comp_fact_func'),
    path('polynomial-root-calculator/',polynomial_root, name='polynomial_root'),
    path('polynomial-root-of-<str:num1>/',polynomial_root_func,name='polynomial_root_func'),

    path('polynomial-equation-solver-calculator/',poly_eq_solver,name='polynomial-equation-solver-calculator'),
]