# Generated by Django 3.0.7 on 2022-04-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Differ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('sub_subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000000)),
                ('subject', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='difference_between.category')),
            ],
        ),
    ]
