# Generated by Django 3.2 on 2022-09-12 04:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difference_between', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differ',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
