# Generated by Django 3.0.5 on 2020-07-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polynomials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_poly_db',
            options={'verbose_name_plural': 'add_poly_db'},
        ),
        migrations.AlterModelOptions(
            name='sub_poly_db',
            options={'verbose_name_plural': 'sub_poly_db'},
        ),
    ]
