# Generated by Django 3.0.5 on 2020-07-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polynomials', '0002_auto_20200714_1929'),
        ('polynomials', '0003_div_poly_db_mul_poly_db'),
    ]

    operations = [
    ]
