# Generated by Django 3.0.7 on 2020-07-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polynomials', '0006_degree_poly_db'),
        ('polynomials', '0004_merge_20200715_1814'),
    ]

    operations = [
    ]
