# Generated by Django 3.0.7 on 2020-08-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polynomials', '0007_merge_20200716_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ascding_poly_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputEnter', models.CharField(max_length=250)),
                ('detailStep', models.TextField()),
                ('finalAnswer', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300)),
                ('solutionTitle', models.CharField(max_length=250)),
                ('date_modified', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'ascding_poly_db',
            },
        ),
    ]
