# Generated by Django 3.0.7 on 2020-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polynomials', '0021_auto_20201022_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact_poly_db',
            options={'verbose_name_plural': 'fact_poly_db'},
        ),
        migrations.AlterField(
            model_name='fact_poly_db',
            name='date_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fact_poly_db',
            name='finalAnswer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='fact_poly_db',
            name='inputEnter',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fact_poly_db',
            name='slug',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='fact_poly_db',
            name='solutionTitle',
            field=models.CharField(max_length=250),
        ),
    ]
